SELECT BOOK_TITLE, BOOK_COST, BOOK_YEAR 

FROM BOOK; 

SELECT PAT_FNAME, PAT_LNAME 

FROM PATRON; 

SELECT CHECK_NUM, CHECK_OUT_DATE, CHECK_DUE_DATE 

FROM CHECKOUT; 

SELECT BOOK_NUM, BOOK_TITLE, BOOK_YEAR 

FROM BOOK; 

SELECT DISTINCT BOOK_YEAR 

FROM BOOK; 

SELECT DISTINCT BOOK_SUBJECT 

FROM BOOK;

SELECT BOOK_NUM, BOOK_TITLE, BOOK_COST 

FROM BOOK; 

SELECT CHECK_NUM, BOOK_NUM, PAT_ID, CHECK_OUT_DATE, CHECK_DUE_DATE 

FROM CHECKOUT

SELECT BOOK_TITLE, BOOK_YEAR, BOOK_SUBJECT 

FROM BOOK 

ORDER BY BOOK_SUBJECT, BOOK_YEAR DESC, BOOK_TITLE; 

SELECT BOOK_NUM, BOOK_TITLE, BOOK_YEAR 

FROM BOOK 

WHERE BOOK_YEAR=2012; 

SELECT BOOK_NUM, BOOK_TITLE, BOOK_YEAR 

FROM BOOK 

WHERE BOOK_SUBJECT='Database';

SELECT CHECK_NUM, BOOK_NUM, CHECK_OUT_DATE 

FROM CHECKOUT 

WHERE CHECK_OUT_DATE < '2015-04-05';

SELECT BOOK_NUM, BOOK_TITLE, BOOK_YEAR 

FROM BOOK 

WHERE BOOK_YEAR > '2013' and BOOK_SUBJECT = 'Programming'; 

SELECT BOOK_NUM, BOOK_TITLE, BOOK_YEAR, BOOK_SUBJECT, BOOK_COST 

FROM BOOK 

WHERE (BOOK_SUBJECT = 'Middleware' OR BOOK_SUBJECT = 'Cloud') AND BOOK_COST > 70; 

SELECT AU_ID, AU_FNAME, AU_LNAME, AU_BIRTHYEAR 

FROM AUTHOR 

WHERE AU_BIRTHYEAR BETWEEN 1980 AND 1989; 

 
