CREATE TABLE CUSTOMER ( 

CustID INT NOT NULL, 

FirstName VARCHAR(12) NOT NULL, 

LastName VARCHAR(14) NOT NULL, 

CONSTRAINT PK_CUSTOMER PRIMARY KEY (CustID) 

); 

CREATE TABLE VEHICLE ( 

VIN VARCHAR(10), 

Make VARCHAR(15), 

Model VARCHAR(20), 

Year INT, 

CustID INT NOT NULL, 

CONSTRAINT PK_VEHICLE PRIMARY KEY (VIN), 

CONSTRAINT FK1_VEHICLE FOREIGN KEY (CustID) REFERENCES CUSTOMER (CustID) 

); 

CREATE TABLE REPAIR ( 

RepairID INT, 

StartDate DATE, 

FinishDate DATE, 

CustID INT NOT NULL, 

VIN VARCHAR(10), 

CONSTRAINT PK_REPAIR PRIMARY KEY (RepairID), 

CONSTRAINT FK1_REPAIR FOREIGN KEY (CustID) REFERENCES CUSTOMER (CustID), 

CONSTRAINT FK2_REPAIR FOREIGN KEY (VIN) REFERENCES VEHICLE (VIN) 

); 

 

INSERT INTO CUSTOMER 

VALUES (1382906, 'Regis', 'Wilson'); 

INSERT INTO VEHICLE 

VALUES ('8A95Q214FR', 'Cadillac', 'Coupe DeVille', 1976, 1382906); 

INSERT INTO REPAIR 

VALUES (5135796, '2020-10-29', '2020-11-05', 1382906, '8A95Q214FR'); 